server:
  port: 8082

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/empDB?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/oauth-server/check_token
    client:
      client-id: web
      client-secret: web